### PR TITLE
begin may 2020 newsletter draft

### PR DESCRIPTION
**Pull request by milancurcic**
Draft newsletter for May 2020. 

To be merged into master on May 1. Work on it until then.

### CODE REVIEW

**Comment by certik** [comment]
This should list all the news items that happened since the last newsletter.

**Comment by milancurcic** [comment]
First draft of May newsletter is up. Please review and suggest edits and/or additions. If you add content, please also add your name to the `author` field in the preamble.

This will be merged into master on Friday, May 1.

**Comment by milancurcic** [comment]
@jacobwilliams Do you have any Fortran positions open in your company to list here?

**Comment by jvdp1** [comment]
Question: could projects like your Fortran-Keras Bridge project be mentioned in this news letter?

**Comment by milancurcic** [comment]
@certik I added a section on WG5 convenor candidates and minor updates to stdlib news. Please review and edit as you see fit. I'm otherwise happy with this newsletter.

**Comment by certik** [comment]
I am ok with the wording for my WG5 run.

**Comment by certik** [comment]
Please do not merge yet.

**Comment by milancurcic** [comment]
@jvdp1 Good question. We discussed the scope to a limited extent in #3 .

I don't know the answer. Originally I thought that personal projects should be out of scope for the newsletter. On the other side, it would be useful for readers to learn of new projects. They would need to be submitted for consideration, i.e. we don't want to list small toy projects that don't build or have docs. There would need to be some criterion on how to do this, like we have for including packages in the registry. I'm curious to hear what other think. Please write in #3. We don't have to rush for this newsletter, obviously we don't have a good idea yet how to do this.

This makes me think of another question: Should we include relevant (Fortran) new papers? I think yes if they're open access. Again, write in #3

**Comment by certik** [comment]
I would not delay this first newsletter, and I would not include personal projects yet. Let's figure out a process for that, and then we can list them in future newsletters.

The same with the job postings, it's kind of arbitrary now, but I think it's fine to list what is in there now to get started. None of these are "our" postings, so nobody will feel that we are just pushing our pet projects.

**Comment by milancurcic** [comment]
Yes, conflict of interest (even non-financial kind) is my main concern for announcing personal projects or job postings. We need a well documented process for this.

**Comment by certik** [comment]
Yes, our main goal and job is to create home for Fortran, a community, tools, a platform for everybody, so we have to be very careful about conflicts of interest. We are in agreement.

**Comment by jvdp1** [comment]
I agree about conflicts of interest. Let see first how the people react to this newsletter.

**Comment by milancurcic** [comment]
Thank you all. The newsletter is up: https://fortran-lang.org/newsletter/2020/05/01/Fortran-Newsletter-May-2020/. Please share it.

**Comment by certik** [comment]
Thanks @milancurcic !

**Pull request merged**
