### PR TITLE
Start tutorials

### PR DESCRIPTION
**Pull request by LKedward**
I've added a stylesheet to enable syntax highlighting and made a start on writing tutorials.

I've put a static preview [here](https://lkedward.github.io/fortran-lang.github.io/pr/tutorials/) to make it easier to view this **draft** pull request.

My idea is to have self-contained tutorials targeting three different programming abilities:

* **For beginners**: quite common to see undergraduates with little programming experience asked to pick up Fortran for science//engineering degrees

* **Intermediate**: for those with basic programming experience using another language like c or python

* **Advanced**: for those who just want to pick up the Fortran syntax and advanced features (OOP etc.)

I also think the _Learn_ section can contain other articles for things like best practices and advanced/niche topics etc.

I'm happy to put work into filling this out since compared to other programming languages there are fewer good quality online tutorials and examples which makes it less accessible.

Happy to hear feedback and ideas.
Thanks for work so far @milancurcic, the site is looking good!

### CODE REVIEW

**Comment by milancurcic** [comment]
Super nice work, thank you! I like most of it. I have some doubts about the 3-level categories of tutorials. I will write more tonight.

**Comment by milancurcic** [comment]
@certik Yes, I think so.

**Comment by LKedward** [comment]
Thanks for the comments @milancurcic; you make some very good points which I agree with.
It shouldn't take long for me to consolidate current content onto the top page by tomorrow morning ready for merging.

**Comment by LKedward** [comment]
I have completed the consolidated content ([preview](https://lkedward.github.io/fortran-lang.github.io/pr/tutorials/learn/)).

For review I ask:
- If I have missed out any fundamental Fortran features?
- What technique should be recommended for real kinds?
  - `kind(0.0)`, `kind(0.0d0)`
  - `iso_c_binding, only: c_float, c_double`
  - `iso_fortran_env, only: real32, real64`

**Comment by milancurcic** [comment]
Regarding your question about kinds, [here](https://github.com/fortran-lang/stdlib/blob/master/src/stdlib_experimental_kinds.f90)'s what we're currently doing in stdlib. This may change in the future, of course.

The higher level issue related to this is the Style Guide. There's currently a very minimal style guide in the stdlib repo, however, I think we should work on a Style Guide here (like a PEP8 for Python) that would then apply to all fortran-lang community projects.

**Pull request merged**
