### PR TITLE
added updated favicon and the png used to create it.

### PR DESCRIPTION
**Pull request by jacobwilliams**

### CODE REVIEW

**Comment by certik** [comment]
I am little confused by the diff ---- there is already a `favicon.ico` file, and you are replacing it, and yet the diff shows your `favicon.ico` as a new file. I would expect it would show replacing it.

**Comment by milancurcic** [comment]
In my email I see it as modified:

File Changes
A assets/img/fortran_logo_64x64.png (0)
M favicon.ico (0)

**Comment by certik** [comment]
Ok. @milancurcic I'll let you merge this one.

**Comment by milancurcic** [comment]
https://raw.githubusercontent.com/jacobwilliams/fortran-lang.github.io/purple-favicon/favicon.ico

Looks good! Thank you @jacobwilliams.

**Pull request merged**
